version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    environment:
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - DYNAMODB_ENDPOINT=${DYNAMODB_ENDPOINT}
    - DYNAMODB_LIBRARY_TABLE=${DYNAMODB_LIBRARY_TABLE}
    extra_hosts:
      - 'cb-library-01.loc:0.0.0.0'
    ports:
      - 3000:3000
    labels:
      com.dnsdock.alias: cb-library-01.loc
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb"
  dynamoclient:
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - DYNAMODB_LIBRARY_TABLE=${DYNAMODB_LIBRARY_TABLE}
    ports:
      - 8001:8001
    extra_hosts:
    - 'db.cb-library-01.loc:0.0.0.0'
    labels:
      com.dnsdock.alias: db.cb-library-01.loc
    depends_on:
      - dynamodb